baseURL: https://kavyamahesh-portfolio.netlify.app/
languageCode: en-us
title: Portfolio Website for Kavya Mahesh
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      LBS - Masters in Analytics and Management
    title: KAVYA MAHESH
    image: brahmatal.jpg
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Gloucester Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: kmahesh.mam2023@london.edu
    enable: yes
    phone:
      - phone: On Request
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Kostis
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com/kostisc
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/kavya_808
      - icon: fa-github
        label: GitHub
        url: https://github.com/Kavya-Mahesh
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/kavya-mahesh98/
  image: ''
  name: Kavya Mahesh
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: aboutme
      - name: Projects
        url: blogs
#      - name: Elements
#        url: elements.html
    menu: Menu
#    subtitle: By HTML5 Up
    title: Portfolio Website
  tiles:
    enable: yes
    showcase:
      - image: lbs_campus1.jpg
        subtitle: A brief account of my professional experience, education and hobbies
        title: CV
        url: blogs/KavyaMahesh_CV.pdf
      - image: chennai_beach.jpg
        subtitle: A glimpse into my background
        title: About Me
        url: aboutme
      - image: brexit.jpg
        subtitle: Brief analysis of Brexit data
        title: Brexit Analysis
        url: blogs/brexit
      - image: pay_gap.jpg
        subtitle: Inspecting influences on pay gap in Bank salaries
        title: Gender Pay Gap Analysis
        url: blogs/salaries
      - image: world_map.jpg
        subtitle: Brief analysis of Life Expectancy and GDP Percap
        title: Gapminder Dataset Analysis
        url: blogs/gapminderanalysis
#      - image: pic05.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "A few of the analytics projects I've worked on at LBS."
    title: My Projects
    url: blogs